// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class WrapCV {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  WrapCV(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  WrapCV.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void laplacian(
    ffi.Pointer<BYTE> data,
    int width,
    int height,
    int ksize,
  ) {
    return _laplacian(
      data,
      width,
      height,
      ksize,
    );
  }

  late final _laplacianPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<BYTE>, ffi.Int32, ffi.Int32,
              ffi.Int32)>>('laplacian');
  late final _laplacian = _laplacianPtr
      .asFunction<void Function(ffi.Pointer<BYTE>, int, int, int)>();
}

typedef BYTE = ffi.Uint8;
